name = "workers-graphql-server"
type = "webpack"

account_id ="67b8bf6d8ad4f483905e8328b8a1ab00"
zone_id = "6906cd55c4af2e5b9dbd592922c66f96"
route = "my-worker.everettjennifer3000.workers.dev"
account_id = "67b8bf6d8ad4f483905e8328b8a1ab00"
zone_id = "6d02ccd4387366f9490f8d7a2e77efcc"
route = "https://workers-graphql-server.everettjennifer3000.workers.dev"
api_key = "5LgipHHJYk1wtKlf-uBuB-TRHtMdTthYYTMGSqAq"

workers_dev = true
webpack_config = "webpack.config.js"
compatibility_date = "2021-10-03"

# Enable a kv-namespace to use the KV caching feature
#
# kv-namespaces = [
#   { binding = "WORKERS_GRAPHQL_CACHE", id = "" }
# ]

[build]
command = "npm install && npm run build"

[build.upload]
format = "modules"
main = "./src/index.js"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"
